### ISSUE TITLE
Usability improvement OK button

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#101]
In NOF7 a form's OK button would respond to pressing the enter key.
In NOF9 this does not seem to be the case anymore.

**Comment by richardpawson** [comment]
You can, in NOF9, tab from the field to the OK button and then hit enter.  

I am not completely sure, but I have a feeling that when developing NOF9 we encountered too many problems (i.e. side effects)  with the idea of hitting enter on the field to OK the dialog  -  for example to do with the possibility that there might be drop-downs, auto-completes etc where the enter has a different meaning. This is one of the challenges of writing generic UIs rather than specific ones.

**Comment by smiltenburg** [comment]
So what I understand is that this functionality is dropped due to technical implementation difficulties. 

In my application we have a lot of input fields in our search forms and therefore tabbing through all of them is not very efficient to reach the' ok' button, this will require more 'mouse action' and a bit of getting used to. No showstopper.

perhaps another key (combination) is easier to implement than 'enter'?
