### ISSUE TITLE
Friendlier message needed if you delete an object, or click on a link to one

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#103]
In my application I sometimes want to delete objects. 
In NOF7 this was done by  adding a delete method (an action) to the object itself and running       Container.DisposeInstance(this);
and then return a string
return "object has been deleted". The user would see the string and it was clear the object was deleted.

In NOF9 the returned string is not visible in the UI, so it lookes like nothing happened. (and pressing delete again triggers an annoying error onscreen)
In order to solve this I looked in the manual how to navigate to the previous screen but found no reference.

How is this situation usually dealt with in NOF9?

**Comment by scascarini** [comment]
You can return Container.WarnUser to tell the user the object has been deleted and navigate to another object by returning it. However the deleted object will still be in your history and will error if you go back to it. You could do some custom error handling to catch this case yourself. 

We could add some special error handling so that if we try to navigate to a non-existent object we provide a more friendly message suggesting the object may have been deleted .

**Comment by richardpawson** [comment]
I think that NOF8 had a more friendly message if you click on a deleted object  -  or if you delete the object in view.  So I'm converting this ticket to a bug that needs fixing.
