### ISSUE TITLE
NOF7 Documentation bug: Unclear "Namespaces" value

### ISSUE THREAD

**Issue by tedneward** [NakedObjectsGroup/NakedObjectsFramework#11]
In the "Writing your first Naked Objects application" section, step 6 says to make changes to the App_Start\NakedObjectsRunSettings.cs file, and uses "MvcTestApp" as the value; from the context, I infer that this should be "MyWebApp", but this should be made more clear. (I'm not positive that this is the right value, by the way, since going through the tutorial does not yield a working app with NOF7 as of this writing.)

**Comment by richardpawson** [comment]
Sorry, I am aware that with NOF7 we rather neglected the 'getting started' aspect of the documentation, and it got rather out of date.  We have been trying to improve this for NOF8 (still in Beta), whence the link to the .zip of an ultra-simple NOF8 example from the ReadMe.  I will tomorrow create a retrospective equivalent for NOF7 and add that into the 7.0 repository, and correct the errors in that part of the NOF7 manual you have highlighted. Meantime, if you are trying the framework out for the first time, I would recommend trying NOF8 anyway.

**Comment by tedneward** [comment]
Trying it now; just filed a bug(?) with NOF8. Personally I prefer the NOF8 approach (HTTP API + SPA front-end), particularly if I can (at some point down the road) replace the NOF8 front-end with a custom one a la Angular2 or something. More flexible that way. :-)

**Comment by richardpawson** [comment]
Yes, NOF8 would facilitate that.  You could write a completely custom front end from scratch that talks to the RO server.  More likely you would make use of our client libraries for handling the returned representations -  with lots of helpers.  They are written in Angular 1.5.  We will move to Angular 2 when it had stabilised  -  that was just a bridge too far for NOF8.  Incidentally, when you get NOF8 running, explore both the Gemini (GUI) and the Cicero UIs  (sketch details of the latter in the manual).  Cicero is intended for non-sighted users, but I raise it here only because it is a _completely_ different style of UI but constructed from the same underlying NOF/  Angular library.
