### ISSUE TITLE
How to order result by column

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#116]
Hi, 
Currently our application has a search action for each entity type and this displays a paged list of the searched entity type.
I return these results ordered on a certain "default" property, but this is not always what a user wants. 

I would like my users to be able to click on the column header to override the default sorting.
Even better would be to also have some extra filter ability from within the result set.

**Comment by richardpawson** [comment]
On your first point, we have considered this several times, but concluded it isn't practicable for a generic UI.  So the answer is, just change your action to include an drop-down list of order-by columns -  either make it optional or provide a default sort order.

Also: encourage users to learn to right-click on OK for query actions like this, so that the dialog remains open on the left.  Then it is a simple matter to specify different ordering.  The same can apply to filtering.

Sub-filtering (using collection-contributed actions) is not possible (in NOF) on an IQueryable -  for reasons of query complexity over Http.  The only way to do this (though I would not encourage it) is to return a List rather than an IQueryable  -  then you can use collection-contributed actions.  But you must be careful to limit the list  -  effectively providing your own paging mechanisms, by providing parameters on the original query action for page size, page number.  Personally I wouldn't do it.
