### ISSUE TITLE
documentation error? /rest

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#119]
Hi, 
In getting my application published to azure I had to change the appPath in my config.json.
From the demo / sample project and debugging the value is http://localhost:5000/

Since my deployment was not successfull in the first try I headed down to the documentation and the troubleshooting section. Since there are there are multiple referencec to a path with "/rest" appended to it this got me doubting.

"appPath": "http://localhost:5000/rest"

removing it seemed the way to go.

So I think this is an error in the documentation

**Comment by richardpawson** [comment]
The appPath needs to match whatever Url the server puts out the Restful API on.  (You either need to scratch the /rest from the appPath  OR configure the server to add the '/rest'.)

We used to append /rest onto the Url deliberately (though that was always configurable) for the Rest API, to distinguish it from the MVC server Url (this was NOF7).  Now we don't bother, because there is no MVC API any more.  So, sorry, some of the documentation is probably out of date on this point  -  I will check and fix now.

**Comment by richardpawson** [comment]
Now corrected
