### ISSUE TITLE
datemask has no effect

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#120]
Hi, 
my users would like a different date format (31-12-1981)

- The datetime property on my object has been annotated with [Mask("d")]
- The config.json has been adjusted to

```
 "dateMasks?": {
      "d": {
        "format": "date-time",
        "mask": "D MM YYYY",
        "tz": "+0000"
      },
```
but I saw no effect in the UI. 

Not even when I re-arranged the default values to a different order 

``` "dateMasks?": {
      "d": {
        "format": "date-time",
        "mask": "D YYYY MMM",
        "tz": "+0000"
      },
```
It looks like this setting is not picked up in view /edit mode.

**Comment by richardpawson** [comment]
I just took a quick look at this (I don't have much time) and there does seem to be something not working properly  -  we will need to investigate further.  But **for now** remove the question-mark from:

 "dateMasks?": {

(I know it has ? in both the documentation and the template  -  I need to investigate why that is/was)

then try altering the format capital D option (i.e. using Mask("D") in domain code ).  I got this to work fine, but, like you, could not get the format of the lower-case d mask to change.

**Comment by smiltenburg** [comment]
Hi Richard, thanks for the quick reply, however it works only partially.

When I remove the questionmark after dataMasks in the config.json it does seem to listen to the capital D for the "read" variant of my object, but when I edit the object the date is still shown in the "DD MMM YYYY" format.

for reference this is my property's annotations (and it also shows that my property is nullable)

```
        [MemberOrder(1011)]
        [Mask("D")]
        [DisplayName("Geboortedatum")]
        [Optionally]
        public virtual DateTime? GeboorteDatum { get; set; }
```

**Comment by richardpawson** [comment]
After further investigation, there is no bug here. Quoting from the manual:

_By default, a DateTime property will be displayed to the user as a ‘date
only’, with the time element ignored. The date will have the same value
irrespective of the timezone of the client (browser). The default format is
d MMM yyyy (e.g. 3 Jul 2016). If you use a mask to forces the display of a
time, then this will always be shown as zero, because the time component is
not transmitted between client and server._

Even if you specify a mask that includes the time element, you will not get the time displayed on the client, because the data will have been passed through the RO API as a date only  -  and will be time-zone independent.

To display a DateTime property with both date and time elements, you will need to do the following:

1) In your C# domain code, add the annotation:

**[DataType(DataType.DateTime)]**

2) Also in the C# code, on your DateTime property, specify a suitable Mask annotation so 

3) If the Mask is not equivalent a known standard .NET you will need to configure the mask in the client code, as described above.
