### ISSUE TITLE
upgrading the client

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#122]
Hi,

I am trying to document (for my collegues) what should be done if they would want to upgrade the solution to a newer NOF version (for instance 9.0.0 -> 9.0.2). In the documentation it tells me I just need to upgrade the nuget packages, but in the git repo of the template I can see that the minified javascript files have also been changed.

Is it safe to upgrade by just updating the nuget packages or are there more steps required?

**Comment by richardpawson** [comment]
Provided that you have no customisations then generally it is safe to update the clilent just from the NuGet package -  indeed that is how I upgrade the Template.  The only thing to be careful of is not to overwrite any files that you have (necessarily) altered (i.e. the config.json).

Occasionally it may be necessary to modify/extend config.json, but we will then alert you.  For example, we are still looking into your question about Date formats - but it is apparent that the question-mark was a bug and should not be there, so that would be such a change.
