### ISSUE TITLE
Documentation on Internationalisation / Localisation is missing in the NOF 9 manual

### ISSUE THREAD

**Issue by bvdoord** [NakedObjectsGroup/NakedObjectsFramework#124]
Hi there,

I'm still learning my way around NOF 9 and so far the manual has been a helpful resource. However, I'm trying to localise my application and the section for that seems to be missing from the manual. Searching through the manual with ctrl + F looking for related terms only finds one paragraph on page 43, which references a section that doesn't seem to exist (clicking on it gives an error).

Localisation seems to be possible from that paragraph, but I have no idea how to go from there.

Thanks in advance

**Comment by richardpawson** [comment]
Localisation was fully implemented from quite early on in the NOF.  If you look at the Developer Manual for NOF 7.0 (https://github.com/NakedObjectsGroup/NakedObjectsFramework/blob/7.0/Documentation/DeveloperManual.docx ) you can see a more complete explanation.

However, I have a feeling that we removed that section of the documentation (accidentally leaving in the  reference to it that you saw) when we moved to NOF8  -  very possibly because we never thoroughly tested it.  (In all the years of NOF we are not aware of anyone having actually used the localisation capability!)

So far as I know, it _should_ still work, but that's not any guarantee!  Certainly the way you _run_ with localisation would have changed with NOF8  -  because that's when we started configuring the framework via the Unity framework.  But that bit is mentioned in the NOF9 manual.  The (much longer) NOF 7 section on this topic explains how to generate the resources file for changed strings.  I can only suggest giving it a try, and apologise that this aspect of the framework is not now well documented or guaranteed to work.  Please report back.
