### ISSUE TITLE
How to display currency other than GBP or specify custom formatting?

### ISSUE THREAD

**Issue by dannief** [NakedObjectsGroup/NakedObjectsFramework#138]
I want to display currencies as $100.00 or JM$100.00. However if I change the symbol to `JMD` for `$` in the `config.json` file, then no value is displayed at all. What are the supported values for `symbol` in the `config.json` and can the values be updated? So far I see that `GPB` displays '£' and `USD` displays `US$`.

Also how can I create a custom display format for a value in view mode? (I was thinking I could do this as an alternative to using a Mask. ) I think maybe this can be done in an IViewModel, but that would be overkill to change the format for one property. Is there better way?

**Comment by dannief** [comment]
I am going to partially answer the first question....I went ahead and dug into the source code and found the `mask.service.ts`. I determined that I needed to set the `locale` like so
```javascript
"C": {
    "format": "decimal",
    "symbol": "JMD",
    "digits": "1.2-2",
    "locale": "en-JM"
},
```
This displays the currencies like `JMD100.00`, which I am OK with. I also determined the Angular `CurrencyPipe` is being used behind the scenes so that currency formatting is necessarily limited by the `CurrencyPipe` functionality.

However, I am still curious if I will be able to achieve custom formatting at the property level.

**Comment by richardpawson** [comment]
To do any further customisations, beyond what we specify in the manual, you would have to write custom components in Angular.  You can also make use of the PresentationHint attribute in the domain code to provide hints that custom client components can pick up on (because those hints go through the ApI).

But  -  a word of caution.  The power of Naked Objects comes from keeping the focus on the domain model and logic, not on customisation.  The earlier you get into customisation of the UI the easier it is to lose the power of Naked Objects.  We've seen that happen  -  unnecessarily  -  too many times.

**Comment by dannief** [comment]
> But - a word of caution. The power of Naked Objects comes from keeping the focus on the domain model and logic, not on customisation. The earlier you get into customisation of the UI the easier it is to lose the power of Naked Objects. We've seen that happen - unnecessarily - too many times.

I do agree. This is why I think It would be good to have a way to easily customize the view or how values are displayed without having to create custom components.

I think there are good suggestions made in issue #121. So will continue the discussion there.
