### ISSUE TITLE
NOF8 Table View error with collection properties

### ISSUE THREAD

**Issue by NateEichenlaub** [NakedObjectsGroup/NakedObjectsFramework#14]
I receive the following error when trying to display a collection in table view when one or more of the properties is a collection property: 

> TypeError: propertyRep.entryType is not a function
>     at viewModelFactory.propertyTableViewModel (nakedobjects.services.viewmodelfactory.ts:494)
>     at nakedobjects.services.viewmodelfactory.ts:887
>     at lodash.js:3063
>     at lodash.js:4141
>     at baseForOwn (lodash.js:2667)
>     at lodash.js:4110
>     at baseMap (lodash.js:3062)
>     at Function.map (lodash.js:8032)
>     at viewModelFactory.tableRowViewModel (nakedobjects.services.viewmodelfactory.ts:887)
>     at viewModelFactory.itemViewModel (nakedobjects.services.viewmodelfactory.ts:186)

**Comment by richardpawson** [comment]
Can you elaborate a bit -  as this is not an issue we've come across yet.

1. Are you talking about a table view of a returned query, or a table view of an object's collection property, or both?

2. Are you explicitly including a column in the TableView attribute that is itself a collection property, or is this just the unconstrained table view?

**Comment by richardpawson** [comment]
I have deleted my previous posting, because I'd forgotten that we don't support the rendering of collection properties as columns within a table view.  My memory is that we didn't support that in any previous version  -  unless you tell me otherwise.  If so, then what is needed is just a clearer comment in the documentation, and to fail more gracefully (e.g. just ignore it as we do with any column name that doesn't match any property).

**Comment by NateEichenlaub** [comment]
Collection properties were supported in table views in NOF7, with the column displaying the collection's record count. The RO collection representation with "x-ro-inline-collection-items=true" seems to support this, as collection properties contain a "size" property in place of "value".

**Comment by richardpawson** [comment]
Fixed in Beta6  -  just released.
