### ISSUE TITLE
ContributedAction only recognise one of more than one selections

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#166]
Updated to NOF 10, but problem persists: a contributed action shows up when the appropriate type is listed, but checking multiple items and invoking the contributed action only sends through one of the selections (I presume the first in the list, but have not checked).

This is the type of contributed action where the parameter to the action is of type "IQueryable<Item> items", and where the contributed action is defined on a repository / service so that it can apply to any ad hoc collection of type Item.

I can remember experiencing this before, and thought upgrading might solve it.  Note that contributed actions on collections of a particular object works fine (where the parameter to the contributed action is of type "IEnumerable<Item> items").

This is a problem when attempting to define a contributed action such as "Delete" or "Rename" to delete or rename all selected items. As explained, each time the action is invoked only one of the selections makes it into the contributed action, the rest is silently dropped.

**Comment by richardpawson** [comment]
I am wondering if the issue is specifically because you are Deleting or Renaming the objects.  Possibly, that is confusing the system because the deleted object or renamed object is no longer visible.  You could first of all verify that the query-contributed action works as expected for an action that neither deletes objects nor changes their title.

**Comment by VantageKR** [comment]
No, unfortunately not it seems.

These are the details:

* An action called List returns IQueryable<T>.

* The result of List is displayed in a table, with the checkbox to the far left for doing multiple selections.

* The result of List spans multiple pages, so the paging actions also show up.

* The contributed action (call it Rename) shows up on this results from invoking List.

* The type T is abstract but has various concrete implementations.

* The contributed action Rename only does "this.Container.InformUser()" with the count of the number of items, which is always 1 even when multiple items were selected - to repeat - Rename does nothing except obtain the count of the list of items and calling InformUser() to display the count.

**Comment by VantageKR** [comment]
No, unfortunately not it seems.

These are the details:

* An action called List returns IQueryable<T>.

* The result of List is displayed in a table, with the checkbox to the far left for doing multiple selections.

* The result of List spans multiple pages, so the paging actions also show up.

* The contributed action (call it Rename) shows up on this results from invoking List.

* The type T is abstract but has various concrete implementations.

* The contributed action Rename only does "this.Container.InformUser()" with the count of the number of items, which is always 1 even when multiple items were selected - to repeat - Rename does nothing except obtain the count of the list of items and calling InformUser() to display the count.


On 04/07/2019 20:57, Richard Pawson wrote:

I am wondering if the issue is specifically because you are Deleting or Renaming the objects. Possibly, that is confusing the system because the deleted object or renamed object is no longer visible. You could first of all verify that the query-contributed action works as expected for an action that neither deletes objects nor changes their title.

**Comment by VantageKR** [comment]
Further on this...

Bizarrely, this issue is not present when invoking the same contributed action on a list obtained by an action method on some object that itself has a collection of the items returned; in this scenario, the multiple selected items is correctly received by the contributed action.

For example, class Person has a collection Addresses that is eagerly loaded when viewing Person. If you view some instance of Person, and then use an action on Person to filter the addresses for the person to only show a subset, and on that subset select more than one Address, and then use a contributed action such as Remove, all works great.

However, invoking an action on Company (which in turn has a collection Persons) to list all matching Address items for all Person items in Company, to obtain an identical list of Address items, the very same contributed action Remove only ever receives one Address item.

How would I even go about debugging this? The UI seems to function fine, but I have not run a Fiddler HTTP trace yet.

Should I be building NOF from source?


On 04/07/2019 20:57, Richard Pawson wrote:

I am wondering if the issue is specifically because you are Deleting or Renaming the objects. Possibly, that is confusing the system because the deleted object or renamed object is no longer visible. You could first of all verify that the query-contributed action works as expected for an action that neither deletes objects nor changes their title.

**Comment by richardpawson** [comment]
> Should I be building NOF from source?

No.  First of all use Fiddled to determine whether the payload is correct i.e. the set of objects that you have selected is being passed back from the UI to the server as the arguments for the action, and that the Ids for those objects all look correct  -  the same way for the case that works and for the case that doesn't. I think it unlikely that this is where the issue is, but it is worth eliminating.

NOF is not infallible, but I have to say that this does not '_smell_' like a NOF bug me.  I suspect there is something more unusual in your code than you are telling us -  if not in the action itself then perhaps in the objects you are calling it on. 

Rather than delve into the NOF source, I suggest that you  concentrate on creating a _minimal_, standalone demo that reproduces the problem.  If it is a NOF bug then we will such a standalone example in order to reproduce the bug and fix it. But I _suspect_ that in attempting to create this minimal demo you might well find out what the real cause of the issue is in your own code.
