### ISSUE TITLE
NakedObjects 7.1.1

### ISSUE THREAD

**Issue by mail2mhossain** [NakedObjectsGroup/NakedObjectsFramework#17]
In my project I am using NakedObjects 7.1.1. But recently I have found that NakedObjects 7.1.1 has been removed from NuGet. Is there any issue in NakedObjects 7.1.1?

**Comment by richardpawson** [comment]
We withdrew the 7.1 release many months ago -  last September/October I think. You can view details on the Releases tab in this repository. It was not due to any fault, but because we decided not to pursue the direction we were starting to go with 7.1, and instead focus on NOF 8 (for which we have recently been issuing weekly Beta releases and will soon go to 'RC1').

I recommend you downgrade from 7.1 to the latest stable 7.0 release -  as 7.1 is not supported.  7.1 had introduced a couple of new attributes, which have now gone, but you probably weren't using them anyway.  (We will introduce them again in a future release, but not 8.0  -  as it is important for us to stay with the 7.0.3 programming model).

Note that though the 7.1 packages are de-listed from NuGet, they can never be deleted  -  you can always install them if you know the actual package version you want.
