### ISSUE TITLE
Upgraded to NOF 10, but application properties lists older version of API

### ISSUE THREAD

**Issue by VantageKR** [NakedObjectsGroup/NakedObjectsFramework#172]
After having upgraded all Nuget packages to their latest versions, when viewing the application properties in the client, I get this:

```
Server API version: 8.1.3
 
Client version: 10.0.0 
```

Why would this be: why would the server API version not also be on 10?

**Comment by richardpawson** [comment]
As you know, NOF consists of many components, each with their own APIs. Our policy is only to move up a version of a component if it has in fact changed.  The server API version (as shown on the client) is not the version of all the different components in the server, it is the version of the Restful Objects API component that provides the entry into the server. This has (deliberately) not been changed since NOF 8.  Similarly, the ProgrammingModel component is still at version 7.0.4 -  it has not changed since NOF 7.

**Comment by VantageKR** [comment]
Thanks a lot Richard, that clarifies it. I have in fact noticed that the coupling between the client UI and the server API is so low that things keep working even when using say the NOF 9 client, and the NOF 10 server API. Very nice!
