### ISSUE TITLE
Issue: Menu Hiding based on Role, Issue in NO 7.0 BUT not in NO7.1

### ISSUE THREAD

**Issue by mail2mhossain** [NakedObjectsGroup/NakedObjectsFramework#18]
1. - I have attached a sample projects with DB. Please attach the DB first. By default admin user is “admin@gmail.com” and password is “123456”.
2. - If I logged in with admin user first time, it is working fine. It showing two menus (Area and User Accounts) as per permission.
3. - Then I am logged out and logged in again with a different user name “mail2mhossain@gmail.com” and password is “123456”. But still it is showing two menus. But this user does not have permission on “User Accounts”. It has permission only on “Area”. If I click on any sub-menu of “Area”, it is working. But if I click on any sub-menu of “User Accounts”, it is showing error. 
4. - If I run again the project, then it will show only one menu (Area) as expected.

BUT this problem is not present in NO 7.1
[NO7TestSolution.zip](https://github.com/NakedObjectsGroup/NakedObjectsFramework/files/373114/NO7TestSolution.zip)

**Comment by richardpawson** [comment]
I 'm guessing that the reason is that the browser has cached the home page - such that it has survived between the two sessions.  But when you then try to invoke the (now-disallowed) User Accounts menu the server denies permission (correctly) and hence the error.

What happens if, after logging in as the second user, you refresh the page in the browser?  

I think the problem with fixing this, from memory, is that this is all under the control of ASP.NET MVC, not Naked Objects  -  and I don't think we can force the browser to clear its cache.  

N.B. I can't, though, think of any reason why this would work differently between NOF7.0 and NOF7.1
