### ISSUE TITLE
Automatic closing of a tab

### ISSUE THREAD

**Issue by brentvee** [NakedObjectsGroup/NakedObjectsFramework#25]
Hey Richard,
Hope you're well

We have a scenario where a user would click an action on entity A, say, 'ConfirmData'.
This then opens up a second entity tab with entity B that the user needs to confirm. Entity B has two actions 'Confirm' and 'Reject'. 
It would be rather nice if after the user clicks the 'Confirm' action on entity B, the tab for that entity closes and NOF takes you back to the previous tab, which in this case would be the entity A again.
Perhaps an attribute on the action?
Just a suggestion for improving the user experience.

Thanks

**Comment by richardpawson** [comment]
Brent

Please note that we have now released NOF 8, which has two significances:

1. There are no tabs in NOF8. However, the split pane capability might be useful in your scenario.

2. NOF8 is now the supported version: we aren't planning further improvements to NOF7.

Note also that if entity B has knowledge of entity A, then your Confirm and Reject actions could simply return entity A (instead of 'void' I assume) and this would have the same effect.

Richard

**Comment by brentvee** [comment]
Cool thanks Richard,
I am planning on getting NOF 8 up and running when I have time.

Thanks for the NOF 7 suggestion.
