### ISSUE TITLE
One to One Relationship (NO7)

### ISSUE THREAD

**Issue by mail2mhossain** [NakedObjectsGroup/NakedObjectsFramework#26]
[NO7TestSolution.zip](https://github.com/NakedObjectsGroup/NakedObjectsFramework/files/399112/NO7TestSolution.zip)
I have two classes Person and PersonAddress with one to one relationship as follows.
public class Person
    {
        [Key, NakedObjectsIgnore]
        public virtual int PersonId { get; set; }
        [MemberOrder(20)]
        [Required]
        [MaxLength(150)]
        public virtual string FirstName { get; set; }
        [MemberOrder(30)]
        [MaxLength(150), Optionally]
        public virtual string LastName { get; set; }
        [MemberOrder(100)]
        [Required]
        public virtual PersonAddress Address { get; set; }
    }
public class PersonAddress
    {
        [Key, NakedObjectsIgnore]
        [ForeignKey("Person")]
        public virtual int PersonId { get; set; }
        [MemberOrder(20)]
        [Required]
        [MaxLength(150)]
        public virtual string Street { get; set; }
        [MemberOrder(30)]
        [MaxLength(150), Optionally]
        public virtual string Country { get; set; }
        [MemberOrder(100)]
        [Required]
        public virtual Person Person { get; set; }
    }
I am trying to create both at a time with following codes

public Person AddPerson(string firstName, string streetAddress)
        {
            Person person = Container.NewTransientInstance<Person>();
            PersonAddress address = Container.NewTransientInstance<PersonAddress>();

            person.FirstName = firstName;
            address.Street = streetAddress;

            address.Person = person;

            Container.Persist(ref person);
            Container.Persist(ref address);

            return person;
        }
BUT FAILED

ALSO.
IS THERE ANY WAY TO LOAD CONTEXT AS PER USE CASE THAT IS AS PER BOUNDED CONTEXT. I DO NOT WANT TO LOAD ALL CONTEXTS IN MEMORY, WANT TO LOAD AS PER USE CASE.

**Comment by richardpawson** [comment]
Thanks for posting the .zip example, that is helpful.  I haven't opened it yet, but may do later on  -  this is a quick reaction. What you want to do is certainly possible.

Not having run it yet, I'm not sure exactly what error you are getting or where it is bring thrown, but looking at the code sketch above, the line 'Container.Persist(ref address);' should not be necessary, and I am thinking it would result in an error saying that the address is already persisted.  This is because when you persist the person (in the line above) the framework should be automatically persist any other transient objects that the person has a reference to  i.e. the address. I would be inclined to write it this way i.e. set up the association from the person end and persist only the person:

```
public Person AddPerson(string firstName, string streetAddress)
{
Person person = Container.NewTransientInstance();
PersonAddress address = Container.NewTransientInstance();

        person.FirstName = firstName;
        address.Street = streetAddress;
        person.Address = address;
        Container.Persist(ref person);
        return person;
    }
```

If that still doesn't work, please post the error message.

On your second question, can you provide more explanation of what you mean exactly by 'context'.  Do you mean one of several DbContexts, or one of several parts of the model? If the latter, what do you mean by 'loading' it? What is the real issue you are trying to address by having multiple contexts?  Note: I build huge models in Ireland (5000 domain classes) and though we manage the model as lots of isolated 'clusters' (see description in Naked Objects Developer Manual) they are all loaded all the time.

**Comment by mail2mhossain** [comment]
It is working now as per your suggestions. Thank you very much, Richard.

My Second question is -
I want to implement the concept of "Bounded Context" of DDD. So I want separate context project based one each Bounded Context. If I do not use NO, then I'll create my own context, UoW, Repository and will use as per useCase (Bounded Context). in the attached project, I have AreaBoundedContext and UserAccountBoundedContext. Use Case of these are different and they never interact each other. So, when Area feature will be used, I want to load only AreaBoundedContext not UserAccountBoundedContext. If I do not use NOF, then I'll do it 
using (AreaUnitOfWork uow = new AreaUnitOfWork())
            {
                AreaRepository repo = new AreaRepository(uow.CurrentObjectContext);
                DataLog data = repo.UpdateDataLog(dataLogId,status,remarks);
                uow.CurrentObjectContext.SaveChanges();
            }
It will load only the AreaBoundedContext and dispose it after finishing the work.

**Comment by richardpawson** [comment]
On your second question:  you've confirmed what I suspected you meant, but hoped you didn't. 

I have to stay that I have read a lot about that pattern and I can see no value in it.  Indeed, I think that this pattern has seriously derailed the whole DDD  movement: if you look on the DDD forums, most of the discussion is about technical implementation issues not domain modelling.  I think that Naked Objects has stayed far truer to the original philosophy of DDD than things like CQRS which now dominate the discussion.

Arguably the advantage is that it is more optimised  -  you create fewer instances.  But, as I mentioned before, I build huge models in NOF and this overhead is tiny.  The only performance issues we have ever encountered are to do with either poor design of the domain model, or horribly inefficient queries to the database.  

I'm afraid I don't know how you could implement that UoW/Bounded Context pattern using Naked Objects, and my best advice is not to bother  -  it will only damage your domain model, not help it.

(As I said before, though, it **is** important to break up a large domain model into well-isolated chunks, in order the manage the development process, and avoid the model turning into a big plate of spaghetti.  Our recommended pattern for that is the 'cluster pattern' as described in the manual.  FYI, a further stage is to turn the clusters into separate NuGet packages.)

**Comment by mail2mhossain** [comment]
Got your point. But wanted to implement micro-services based on Bounded Context. Though it is possible to implement micro-services without use of Bounded Context. May be "Cluster Pattern" will help me in this regard. I'll go through "Cluster Pattern" and will see how to implement in NO. Thanks again.

**Comment by richardpawson** [comment]
I have to say I'm not a fan of the micro-services architecture either!
