### ISSUE TITLE
Dropdown Choises are passing null values

### ISSUE THREAD

**Issue by konradcwalina** [NakedObjectsGroup/NakedObjectsFramework#27]
Hi,
I'm trying to create a multiple choice box based on the object list.

**The dropdown object:**
 [DisplayName("Document Type")]
    public class DocumentType
    {
            [NakedObjectsIgnore]
            public virtual int? Key { get; set; }
            [NakedObjectsIgnore]
            public virtual string Code { get; set; }
            [Title()]
            public virtual string Title { get; set; }
    }

**The Choises method:**
public IEnumerable<DocumentType> Choices3ShowDocuments()
        {
         var list = new List<DocumentType>();
         .......
         return list;
        }

**The query form method:**
     [QueryOnly]
        public DocumentListVM ShowDocuments(
            [ContributedAction(SubMenu)] ICustomer customer
            , IEnumerable<CustomerDocumentSource> sources
            , DocumentTypeCode documentSourceType
            , IEnumerable<DocumentType> documentTypes
                ){....}

All options are showing correctly in the multi choice box, but after submitting the form, I have a list of selected items with all properties set to null. In example, if I select 3 positions from the list, I have 3 elements in the documentTypes parameters, but all values (Key,Code,Title) are null.

Thanks in advance for any help.
Konrad

**Comment by richardpawson** [comment]
Can you confirm that the DocumentType objects are already  _persisted_ before they are returned from the Choices3ShowDocuments() method  -  that isn't clear from the code.

(Not revelant to your query, but just general advice:

 No need for:
[DisplayName("Document Type")]
public class DocumentType

as DocumentType will format to "Document Type" on the UI. Only use DisplayName where you can't use the correct name in code e.g. because you want it called "Document & Type".  Over-use of DisplayName, I find, makes developers lazy about renaming their identifiers in code, which is a better discipline, and makes it harder to find the method in code corresponding to something on the UI.)

**Comment by richardpawson** [comment]
Closed due to no further response.
