### ISSUE TITLE
How to ensure that a long-running batch (.exe) process picks up changes in the database made by an MVC app

### ISSUE THREAD

**Issue by mail2mhossain** [NakedObjectsGroup/NakedObjectsFramework#28]
A NO exe is running permanently. It is using some configuration value that updates from NO MVC. 
BUT NO exe context dos not reflect the new value. It holds the old value. After restarting of NO exe, it is loading the new values.

**Comment by richardpawson** [comment]
I'm not quite sure what kind of configuration values you are referring to, but if they pertain to the start-up procedure of .exe (e.g. the services registered, or the domain model to reflect over) then these can **not** be updated on the fly  -  you _would_ need to restart the .exe.  If you are talking about picking up configuration parameters within domain code then this should be possible.  Please provide more detail.

**Comment by mail2mhossain** [comment]
Say, we have a threshold value for some calculation and it is set by the NO MVC project. After that we have run the NO exe for permanently and it is doing calculation based on configured threshold value. After a while, some threshold values have been changed by NO MVC. But NO exe is doing the calculation using old values NOT the updated threshold values.

**Comment by richardpawson** [comment]
Are you saying that these 'threshold values' are being persisted in the database (by the MVC app), but the .exe is not picking them up from the database; in other words, presumably, the .exe is using values cached in memory (by the DbContext, presumably) rather than going to the database?  If I've understood it correctly, then the issue might be to do with the lifetime of the DbContext.  But please confirm if my understanding is correct before I look further.

**Comment by mail2mhossain** [comment]
Yes, you are right. the .exe is using values cached in memory (by the DbContext, presumably) rather than going to the database.

**Comment by richardpawson** [comment]
So it depends on what you are doing within the .exe.  If you are just starting up the framework and then running a continuous loop, then you are always going to be within the same DbContext - which will cache query results.  If you want this .exe to run alongside a live MVC application and interact with it (at least in the sense of picking up updated values from the database) then you need to change the set-up, so that on each run through the loop, the Naked Objects Framework is being resolved  -  via Unity that is - afresh.  (In the same way as happens with the MVC app).  If you resolve the NOF afresh, then you will get a new DbContext.  If this is too high an overhead, then you could arrange to do it periodically e.g. run your loop a fixed number of times, or repeatedly until a specified time interval has passed, and then resolve the framework again. But this depends on how quickly you need the .exe to be able to detect those changes from the MVC app.

**Comment by mail2mhossain** [comment]
A little bit code on NOF afresh will help.

**Comment by richardpawson** [comment]
Assuming you are using the .exe as per the manual, you've got something like this:

```
        private static void Main(string[] args) {
            UnityActivator.Start();

            UnityConfig.GetConfiguredContainer().Resolve<IBatchRunner>().Run(new BatchStartPoint());

            UnityActivator.Shutdown();
        }
```

The call to Resolve the IBatchRunner will, in turn, resolve the whole framework.

And then you are looping continuously within the BatchStartPoint, perhaps with a Thread.Sleep to define an interval.

If you put that loop of doing something and then sleeping up a level i.e. within the main loop, then you can Resolve the IBatchRunner, which in turn resolves the whole NOF, either on each pass of the loop or (per my previous point) after n-passes, say.

**Comment by richardpawson** [comment]
Closed due to inactivity  -  assumed to be resolved.
