### ISSUE TITLE
Log warning on Naked Objects

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#306]
One log warning on Naked Objects (when running AW NO server) states:

`Filtering method HideContacts because of property Contacts on AdventureWorksModel.BusinessEntity.`

I guess this is because `HideContacts `is (deliberately) overridden on the sub-class _Person_? But I am not sure why this would be a WARN message - as this is a valid thing to do and it seems to have worked correctly (from a UI perspective).

**Comment by scascarini** [comment]
The reason for this warning is that the method was identified as complementary because of a match to a property somewhere up the hierarchy. I think this was supposed to help with the case where the method doesn't show up and you don't understand why and it's because it accidentally matched a property higher up that you didn't notice. 

Could be just an info, or if confusing could be removed, or the message could be improved?

**Comment by richardpawson** [comment]
I think this message adds little value, because HideContacts on Person is only matched up with Contacts on BusinessEntity if there is a virtual HideContacts on BusinessEntity that has been overridden (which involves writing `overrides `). So I suggest removing it.

However, the reverse situation should be flagged i.e. you have Contacts on BusinessEntity and HideContacts on Person, but there is no HideContacts on BusinessEntity being overridden.  Now the HideContacts will not be recognised and this should generate a WARNing.
