### ISSUE TITLE
Template project - error 500

### ISSUE THREAD

**Issue by ury** [NakedObjectsGroup/NakedObjectsFramework#4]
Hi Richard,
It's been a while and obviously you've been busy :)
I'm taking a look at NOF8, and till now I have a couple of comments:

1. In order to run the template project, I had to re-install all nuget packages. Merely a minor inconvenience.
2. Once the example project is running, there's an IIS Express issue I can't get any lead on.  The webpage states "loading main menus" and after a while I'm getting the following server error text:

_Error message received from server
Message: No message available
Code: InternalServerError(500)
Description: A software error has occurred on the server.
Stack Trace :
No stack trace available_

I didn't make any change to the project.
Is it a permission issue?  Any idea?

Cheers,
  Ury

**Comment by richardpawson** [comment]
Ury

I'm offsite today, but will try to get this sorted tomorrow.  I'm not sure why it is necessary to re-install the packages  on the template proj  -  it might be because there isn't a solution file  -  but I had the same issue this morning.

I think the problem then is that re-installing the packages has over-ridden a couple of key files in the template project.  One is unity.config  -  which contains a lot of critical info.  You can check this by comparing your unity config to the one in the template zip.  Another is the url for the restful api, which is defined in nakedobjects.config.ts  -  try comparing those also.  Not sure if that's all of it  -  will check again tomorrow.

(Another minor annoyance, which we can do anything about is that if you select the option to search for TypeScript types, LoDash installs two files for two versions -  so you get a large number of Typescript compile errors.  One of the LoDash files needs to be deleted.)

**Comment by ury** [comment]
Thanks Richard,
Actually, the one thing that's really blocking me is the 500 error from IIS express...

**Comment by richardpawson** [comment]
Yes, but what I'm saying is that those over-ridden files could be causing that.

**Comment by ury** [comment]
I see.  Will look into it, although I made sure to NOT override any existing file during re-installation.

**Comment by richardpawson** [comment]
OK -  I'll look into this tomorrow morning.

**Comment by richardpawson** [comment]
Ury

Please try downloading the Template .zip file again and starting from scratch.

First, I have fixed the issue with the reference paths, so it should now just build and run, without you having to un-install and re-install the packages!

Second, I think the issue you were then experiencing (as I did yesterday on another PC also) was that it wasn't creating the database successfully, and hence the Restful Objects Server was not starting up, and thence no error message could be passed back -  just a plain 500.  What really puzzles me, though, was that even starting up in debug mode, and with VS set to break on all exceptions thrown, I wasn't seeing any exception.

To make things a bit clearer, I've now put an explicit connection string into web.config, instead of relying on an inferred one by convention.  If the problem still recurrs let me know, but check out the connection string and check that it it _should_ work for you i.e. that you have SQLEXPRESS.  If not try changing the connection string.  I'll have to investigate further, though, because Entity Framework should be throwing an exception if the database is not created.  Please confirm back one way of the other  -  for my peace of mind.

**Comment by ury** [comment]
Here's what I've experienced with the updated project:
- There are no build-time errors anymore.
- In web.config, the assembly for Microsoft.CodeDom.Providers.DotNetCompilerPlatform seems to be missing.
- After I reinstall the above assembly in NuGet (version 1.0.1, not 1.0.0 which is shown as installed in the project's Nuget), I get the following build errors:

Severity	Code	Description	Project	File	Line	Suppression State
Error		Could not copy the file "D:\bootmgr" because it was not found.	NakedObjects.Template			
Error		Could not copy the file "D:\BOOTNXT" because it was not found.	NakedObjects.Template			
Error		Could not copy the file "D:\swapfile.sys" because it was not found.	NakedObjects.Template			

- Before reinstalling the above assembly, the project builds and when I run it, I'm still getting the same 500 error.  It might be related to _my_ connection string (I have SQL Server Developer, not SQLEXPRESS), but there's still no exception I could catch and investigate.

**Comment by richardpawson** [comment]
I'll look into the first point  -  though I don't think that's actually causing the problem.

The 500 error is, I strongly suspect, caused by the database not being created (because you don't have SQLEXPRESS). Because that is failing, the Restful Objects server is not starting up at all. But I do not understand why no exception is bring thrown in start-up -  it should be  -  I had the same issue myself on another machine without SQLEXPRESS

So can you try changing the connection string to something that would work for you i.e. a database server that would allow Entity Framework to create a database for you.

**Comment by ury** [comment]
Yep, works beautifully without re-installing Microsoft.CodeDom.Providers.DotNetCompilerPlatform,
I'm going to play with it a little...

**Comment by richardpawson** [comment]
Just following up: I have removed the (unneeded) references to the DotNetCompilerPlatform from the Template.zip. (That's Roslyn stuff added by default, I think).

And I think I have solved the mystery of why you (and I) were not seeing any exceptions when it wasn't creating the database - in your case because you didn't have SQLEXPRESS. This is something I didn't know about Visual Studio 2015 until just now ...

It seems that even if you have specified -  in the Exceptions Settings window - that you want to break on any CLR exception this does not in fact break if you also have the 'Enable Just My Code' box checked (which is done in a completely different place: under Tools > Options > Debugging > General).  I think that is poor design!

**Comment by ury** [comment]
+ on both.

**Comment by ury** [comment]
Ok, checked it out and these are my findings:

- "Enable Just My Code" isn't checked on my VS.  Which exception(s) in the Exception Settings windows should I check to make the debugger break on the exceptions I'm experiencing during the project initialization?
- I added the "as-is" template project to a solution with a EF Code-First model, and added a simple DAL with a DB context and repositories.  After I realized I have to *force* the browser to refresh, it looks like the project cannot initialize again.  I'm seeing that:

    1. The database isn't created in SQL (the one in the original template project was created successfully).
    2. IIS Express still states that it's running NakedObjects.Template, although I changed the project name in my solution.  Stopping the site on the IIS Express manager doesn't seem to do anything.
I tried to run "my" NOF8 project from a different port, but it didn't change the results: still the same old error 500 message.

(2) above makes it hard to debug (1), as I suspect there could be a "collison" between the "original" template application (which works) and the new one I've created.
Is there something special I should do in order to move the application to a different IIS Express port, or to IIS?  I noticed that the application URL is also hard-coded within nakedobjects.config.js/ts.

**Comment by richardpawson** [comment]
To look for initialisation exceptions I generally just select all CLR exceptions  -  and then when you get the Unity exceptions (which are apparently normal) I just select the option not to break on that exception again.

To change the port, just change it in the project properties, and then change the Url in NakedObjects.config to match it.  The key point to understand is this:  there are two parts to a NOF8 run project. One creates the Restful API, and the other is a single page app that talks to this API. The SPA needs to be told where to look for the Restful API and that's the URL specified in NakedObjects.config.   The NakedObects.Template proj combines the Restful API server and the Spa in one project  -  but they don't need to be.  You can run them in separate projects, which is sometimes clearer  -  however you then have to set up CORS  -  so the all in one approach is intended as a faster way to get started.

**Comment by ury** [comment]
Thank Richard, I'm back on looking into it, and will report.

**Comment by richardpawson** [comment]
FYI, in Beta6 (just released) we have significantly improved the error logging, and switched it on by default in the Template app. If, on starting an app, the client fails to connect to the server, look in the nakedobjects_log.txt file in the project directory.
