### ISSUE TITLE
UI: Date fields display date as one day earlier in object view and edit modes

### ISSUE THREAD

**Issue by dannief** [NakedObjectsGroup/NakedObjectsFramework#423]
I have an entity with a date field. When I select a date from the date picker in edit mode, the date displays as 1 day earlier in view mode.

e.g. I selected `14 April 2022`. This date is saved in the database but is displayed at `13 April 2022` in the UI.

**Comment by richardpawson** [comment]
Please clarify if the following is correct:

1. You start with an empty date field - on a transient object, or a persisted object where you select Edit?
2. You select 14 Apr 2022 from the date picker. I assume this shows immediately in the field as 14 Apr 2022 - please confirm.
3. You save the object, but upon saving the field displays 13 Apr 2022, yes?
4. In the database, however, the corresponding field is correct as 14 Apr 2022?

If so, what happens if you change the date directly in the database e.g. to 22 Apr 2022 and then reload the object? Does it display as 22 Apr or as 21 Apr ?

My immediate suspicion is a mis-match in the time zone settings between client and server - is that possible?

Another useful thing to do would be to use the Browser's developer tools to inspect the payload of the message when you save i.e. what is the representation of the date in JSON being passed up to the server when you save the object. Similarly you can inspect the JSON date value coming back from the server after the save.

**Comment by dannief** [comment]
The problem occurs whether I start with a transient object or edit a persisted object.

In my case, I set the default date to be today's date (e.g. 20 Apr 2022) for a new transient object. In the dialog the correct date (20 Apr 2022) displays in the date field. However on saving, while the correct date is saved to the database (20 Apr 2022) an incorrect date (19 Apr 2022) is displayed in the view. 

When I edit this newly persisted object an incorrect date (19 Apr 2022) is displayed in the field and if I save it with this date, then `19 Apr 2022` is saved to the database  and then `18 Apr 2022` is displayed in view mode

The correct data is being persisted and retrieved from the database. I believe this issue is a UI only issue and probably has to with the fact that the month parameter in JavaScript Date object is zero-indexed. Meaning that that actual date of `20 April 2022` or `20-4-2022`, will actually be represented as `19-4-2022`  in the Date object

**Comment by richardpawson** [comment]
I have checked and we have a significant number of automated tests, including end-to-end Selenium tests, that edit/update date fields and these are passing. I have also just done a manual test and, again, no problem.  

Nonetheless, you are clearly experiencing a problem and we need to get to the bottom of it.  You surmise that the problem is client-side because the database is getting updated with the correct value. It might be in the client, but we don't yet know that: just because the database is correct does not mean that the value communicated between server and client is correct.  Please would you act on my earlier suggestion, and use the browser's developer tools (or another inspection tool like Fiddler) to inspect the JSON message being passed back from Server to Client after the date has been edited.  Find the date field within that JSON and confirm that:

1. The date (i.e. Day) value is correct
2. That the date is _just_ a date i.e. has no time element specified.

If we know that it is coming through the JSON correctly then the error is definitely occurring in the client code - otherwise we can't be sure, and, as I say, we have not been able to reproduce the error as yet.

If it is the client, the next option would be to swap back to the NOF12 client (it should be fully compatible with the NOF13 beta server) and see if that makes any difference.  We have done only minor updates to the Client between v12 and v13 beta, and these are only to update to latest 3rd party frameworks incl. Angular.  It is _possible_ that one of those updates changed the handling of dates, though we are running our Selenium tests against the v13 beta client without problems.

Also, which browser are you using? Have you tried it with any alternate browsers - just to try to narrow the problem?

Going back 10+ years we quite often faced issues with dates - somewhat like the one you are having - arising from client and server being in different time zones, and to the (related) different behaviour of JavaScript and .NET dates.  However, we have not heard of any such issue for some years now, after we switched to representing all DateTime fields as having a _date only_ element by default. But my first reaction on seeing your posting was a sense of _deja vu_ about time zones.

**Comment by richardpawson** [comment]
Although we have not been able to reproduce this issue, we do now have some _inkling_ about what _might_ be causing it. We are fairly sure the error is occurring _server side_ and not client side. Please therefore undertake the action suggested above and show us how the date is represented (in JSON0 _both ways_ - i.e. when it is sent from client to server, and when the updated object is passed back. 

Secondly, please confirm:

1. Whether or not the date field in question is annotated with `[DataType(DataType.DateTime)]`  (generally we do not recommend adding that unless the field is read-only0.

2. What TimeZone your server is running within.

**Comment by dannief** [comment]
Sorry for the delay. I've had higher priority projects that I had to focus on

I had indicated in my earlier response that I had confirmed that the correct date was being persisted and retrieved. I didn't specify, but this was confirmed by inspecting the request and responses in Chrome developer tools.

I am testing on the Chrome browser (latest version). The client and server are within the same time zone, as I an running both on my local machine (localhost).

Some additional information:
* I am displaying the date value in the title of the object (via overriding the `ToString()`). The date displays correctly in the title, since I am creating the string server-side
* When I view the object (view mode), the date displays as one day earlier
* When I edit the object (select Edit), the date displays as one day earlier in the date input field 
* If I select the date value I want, save the object, the correct value is saved in the database, but the date is displayed as one day earlier

**Comment by dannief** [comment]
Are the dates being displayed in UTC?

I took a look at the client code and found this function: https://github.com/NakedObjectsGroup/NakedObjectsFramework/blob/master/Client/nakedobjects-client/restful-objects/src/models.ts#L216

The UTC Date for `April, 20, 2022` (2022-04-20) will be `Tue Apr 19 2022 19:00:00 GMT-0500 (Colombia Standard Time)`

See: https://jsfiddle.net/dannief/atfv8u0r/20/

**Comment by richardpawson** [comment]
Thanks for your latest posting. We are now persuaded that the issue lies in the client and are investigating right now. However, the method:

`export function getUtcDate(rawDate: string): Date`

is behaving as it was intended to. The fact that you are getting the previous day displayed (when the browser is in a later time zone) _when calling this function in isolation_ is expected.  The intent of our code is that all dates are passed around _within the client_ as UTC dates. When you push this directly to HTML (as in your test) it will be automatically converted to a string in the local time (happens transparently by the implicit call to `toString`). Whereas within our framework the intent is that we manage the way a date is presented (i.e. whether or not it should be converted to local time) explicitly in each case.

We think what has happened is that _elsewhere in the code_, the way the date is presented has changed, possibly due to the upgrade of third party framework(s) - and this is what we are now investigating. However, if we can't locate this then we might need to make a bigger change.

**Comment by richardpawson** [comment]
This issue has now been fixed (it was caused by an upgrade to 3rd party packages in the v13 beta).  I have just released a new version of the client NPM packages - v13.0.0-beta02
