### ISSUE TITLE
Returning Transient, NotPersisted, object (with multiple DbContexts) throws exception

### ISSUE THREAD

**Issue by e-manual-goldstein** [NakedObjectsGroup/NakedObjectsFramework#453]
I may have inadvertently caused this through custom configuration but what seems to be happening is that when there is only one DbContext for the Framework to consider, _that_ DbContext is selected for all POCOs (including NotPersisted ones):
```
private EFCoreLocalContext GetContext(Type type) {
    try {
        return contexts.Length == 1 ? contexts.Single() : FindContext(type);
    }
    catch (Exception e) {
        throw new NakedObjectDomainException(Logger.LogAndReturn(string.Format(NakedObjects.Resources.NakedObjects.EntityContextError, type.FullName)), e);
    }
}
```
However, when there are _multiple_ contexts, and FindContext is called, an exception is thrown because the NotPersisted object belongs to none of them:
```
private EFCoreLocalContext FindContext(Type type) =>
    contexts.SingleOrDefault(c => c.GetIsOwned(type)) ??
    contexts.Single(c => c.GetIsKnown(type));
```

There also does not appear to be any way to add Types to the `private readonly ISet<Type> notPersistedTypes` on `EFCoreLocalContext`, which may resolve the issue.

**Steps to reproduce**:

1. Add second DbContext at startup
```
services.AddDbContext<AltDbContext>(options => {
    options.UseSqlServer(Configuration.GetConnectionString("AltDbContext"));
    options.UseLazyLoadingProxies();
});
``` 
2. Register `IEnumerable<DbContext>` as a scoped service to allow injection into EFCoreObjectStore 
```
services.AddScoped<IEnumerable<DbContext>>((options) =>
{
    return new DbContext[]
    {
        options.GetRequiredService<ExampleDbContext>(),
        options.GetRequiredService<AltDbContext>()
    };
})
```
3. Create a new POCO and annotate with NotPersistedAttribute
4. Attempt to return a transient instance of POCO

**Comment by richardpawson** [comment]
Please email me directly - I'd like to know more about what you are aiming to do here.

**Comment by scascarini** [comment]
The only type of objects that should be able to be returned from an action in R are persistent objects, transient instances of persistable classes and view models. 

So the behaviour (throwing an exception because the object is unknown to the databases) for multiple contexts is correct. The reason it doesn't fail for a single context is an optimisation. Checking the contexts for ownership of a type is quite expensive. That can't be avoided for multiple contexts but in the case of a single context we simply always return it to avoid the overhead. That means that in this case the object is returned as if it is a transient - however trying to persist it would fail. 

We could remove the optimisation - but that will slow down all success paths for the vast majority of cases. Note that this code was originally designed for EF6 - it may be worth looking at EFCore to see if there is an efficient check for type ownership in an EFCore DbContext.
