### ISSUE TITLE
Error with HideInClient

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#457]
Hit an error when using a property marked `HideInClient`. The error was when the Snapshot was being built and appeared to suggest that a Key (the name of the property) was being duplicated.

I am increasingly of the view that my request for `HideInClient `was not a good idea - as we should just be using a `ViewModel `instead. Given that it has now (just this week) been released. I suggest:

- Mark `HideInClient `attribute as Obsolete (deprecated) and remove any code supporting it in the framework.
- Remove it from the next full release of the ProgrammingModel(s). 

**However** must check that this same error is not also occurring with `PresentationHint`, for which `HideInClient `is just a specialised case.

**Comment by scascarini** [comment]
The error is caused by the Task object having both a HasTests property and a HasTests action. That's not supported in the RO spec and so fails as we must have a unique id. 

The reason it looks like it's to do with HideInClient is that Hidden was used to replace it and hidden properties are not included in the RO representation. 

I will improve the logging under the this ticket.
