### ISSUE TITLE
Add 'RaiseError' to IContext in Naked Functions

### ISSUE THREAD

**Issue by scascarini** [NakedObjectsGroup/NakedObjectsFramework#494]
Throwing exception from Functional Code doesn't seem very pure. 

Should we add a 'Throw' function to the IContext. Then if an exception is set via it the framework can throw the error.

**Comment by richardpawson** [comment]
Good point. I'm not sure.  One possibility is ...

If you invoke an action that returns` IQueryable<T>` and it contains no entries, that's fine.  

But if you invoke an action that should return a single domain object or type T, and it returns Null (even if T is explicitly Nullable), and your action is directly invoked from the UI (i.e. nothing catches the null() then we could say that the Framework should generate a 404 rather than a null result. What do you think?

**Comment by richardpawson** [comment]
Now documented - so close when completed.
