### ISSUE TITLE
[Optionally] on multiline text field in dialog not working

### ISSUE THREAD

**Issue by richardpawson** [NakedObjectsGroup/NakedObjectsFramework#508]
Example in MetalUp.Express:  Files > Create New File As String.  The  last field is marked [Optionally], but if you leave it blank and click OK, it does not execute and nor is there any visible message as to why.

**Comment by scascarini** [comment]
The initial bug is in domain code (failing to handle the null content when left empty). 

However what's strange is that it should be a '500'. On investigation the GetBytes call in the domain code throws a 'ArgumentException' which the NOF mapping code thinks is coming from the NOF parameter handling code. So we map to a 400 rather than 500.
