### ISSUE TITLE
Delete Object (DisposeInstance) in NO7

### ISSUE THREAD

**Issue by mail2mhossain** [NakedObjectsGroup/NakedObjectsFramework#51]
Say I have a domain class “Customer” and it has an action method Delete(Container.DisposeInstance(this);). Action method is as follows:
public void Delete ()
{
Container.DisposeInstance(this);
}

BUT it is getting error. If anything am I missing? How could I write a Delete Action?

**Comment by richardpawson** [comment]
You haven't included what the error was, but I am guessing that the issue is as follows.

When you invoke a void action on an object, then, when completed, the client returns to the object on which it was invoked.  In this case the void action has deleted the object, so there is nothing to return to. (Note, the client does not know anything about what an action does  -  it does not 'know' that this action was supposed to the delete the object). The same is true in NOF 8, although it is handled in a slightly more friendly manner  -  the user is directed to a view that says that the object requested no longer exists.

Your options, I suggest, are:

1. Make the Delete action return some other object.  I accept that there might not be any obvious object to go to, in which case ...

2. Don't implement the Delete action on the object.  Make it a service action on, say, the Customers menu called DeleteCustomer.  This could take an Id for the customer to be deleted, or, better still, an auto-complete field of type Customer, such that the user could see the Customer object's title before hitting OK on delete.  (Per a previous question of yours, you could include a boolean 'Confirm Delete' field in the dialog also.)

3. Implement Delete as a collection-contributed action on an IQueryable<Customer>.

Richard
