### ISSUE TITLE
Unknown client HTTP error upon initialization

### ISSUE THREAD

**Issue by ury** [NakedObjectsGroup/NakedObjectsFramework#56]
Hi,
I update NOF to v8.2.  When I launch the Web server, I get the following message:

> Error message received from server
Message: Unknown client HTTP error
Code: NotFound(404)
Description: An HTTP error code has been received from the server You can look up the meaning of this code in the Restful Objects specification..
Stack Trace :
No stack trace available

Nothing appears neither on the debug output (I configured exceptions settings per Richard's advice) nor in the log output.
I can verify that both UnityWebApiActivator.Start() and RestfulObjectsActivator.PreStart() pass without any exception, and that the DbContext is **_not_** created.

At this point, I usually mention that the NakedObjects.Template sample code works perfectly, but I'm afraid that this, I'm getting the 6 build errors in Scripts\nakedobjects.viewmodels.ts, stating "Build:Accessors are only available when targeting ECMAScript 5 and higher".

**Comment by richardpawson** [comment]
Hello Ury

Which version have you upgrade _from_ ? (e.g. 8.0, or 8.1)

I ask because 8.1 required that you install TypeScript 2.0. Have you done that? (Not sure if that's the issue here, but it could be).

**Comment by ury** [comment]
I upgraded from version 810, and MS TypeScript is installed on the machine (v2.0.6.0).

**Comment by richardpawson** [comment]
Very odd, because 8.2 was a VERY minor upgrade to client only (nothing to server).  It was only second level because it had a small new feature. 

Also, 8.1 - 8.2 did not involve any change at all to the server side -  only to the client. So if your server is not starting up (you say the DbContext is not being created) then this is not caused by any change in the NOF.

Can you use your source control to see what has changed _other than_ .ts/.js files, which are purely client side?

**Comment by ury** [comment]
Hi Richard,

1. I'm not sure I understand how to perform the test you mentioned ("going direct to the server Url".
2. There is no change in the source files (.cs/.config etc.).
3. Just to make sure, when I break in RestfulObjectsActivator.PreStart(), RouteTable.Routes is empty - is it supposed to be?

Thanks,
  Ury

**Comment by richardpawson** [comment]
nakedobjects.config.ts has an appPath variable which contains the url for the server.  (Check that that hasn't changed i.e. you didn't accidentally overwrite it for the upgrade).

If it is still correct, then attempt to start up the app, and, from a browser that can show JSON (e.g. Chrome with JSONView extension installed), go directly to that URL.  You should get back the RO Home representation (with links for Services, Menus, Version etc).  If not, then the server hasn't started up and the client is protesting that what it is getting back is not Restful Objects (JSON).  

If the server is starting up and delivering the RO JSON representations then something is wrong in the client (e.g. it isn't pointing at the correct server).

**Comment by ury** [comment]
I keep forgetting that chrome is one hell of a client-side debugger.
Once you mentioned it, it only took a second to realize what the 404 is all about.  Actually, there are a few of them (one is the server name you mentioned):

> http://localhost:59949/Content/custom.css
> http://localhost:59949/Content/themes/base/fullcalendar.css
> http://localhost:59949/Scripts/custom.directives.js
> http://localhost:59949/Scripts/fullcalendar.js
> http://localhost:59949/Scripts/custom.directives.js
> http://localhost:59949/[No%20Server%20Name%20Specified]
> http://localhost:59949/Content/custom.css
> http://localhost:59949/Content/themes/base/fullcalendar.css

I will look into each one of them.

**Comment by ury** [comment]
ping?

**Comment by richardpawson** [comment]
I was under the impression you had found the problem and resolved it, Ury. I assumed you had restored the deleted files from your code versioning.  If there is still a problem, please take the time to explain the current situation clearly, rather than leaving the onus on me to figure out where you are at.

**Comment by richardpawson** [comment]
In regard to the missing .css and .js files, this was a mistake on our part  - those files are for our own internal testing of customised views, and should not have been included in the Index.html page as references  -  I will correct this in 8.2.2.  However, those missing files are not relevant to normal operation of NOF, and should not have caused you an issue -  the browser should just ignore missing files like that.

Your main problem, I assume, was (as I had suggested early on) that you had over-written the nakedobjects.config.ts, and hence your client was not pointing at your server.  Hence the reason why I assumed you were running again.  If you are not able to run, now that you have restored nakedobjects.config.ts, please advise what is now happening.

Please note that, in general, when you upgrade the nakedobjects.spa package you need to watch out for overwriting any files that you may have modified  -  in particular any of the *.config.ts  files.  But the NuGet Package Manager should have warned you about this anyway.  You might have hit the (overwrite file) 'Yes to All'  button without realising it. That's why I suggested looking in your code versioning to see what changes had been made.

**Comment by ury** [comment]
Thanks Richard.
The client-side files are still "vanilla" - I haven't touched them at all (at least until now, when I updated the server name).
Once I deleted the "custom" scripts, I'm getting a different error message:

> Message: promiseCallback.headers is not a function
> Code: No code available
> Description: No description available.
> Stack Trace :
> No stack trace available

I might be missing something regarding the installation process, sorry about that.  I assume that I _should_ overwrite NOF source files if I didn't change them.

**Comment by richardpawson** [comment]
I can't really diagnose this at a distance, without any clues. I suggest that, for the time being, you revert back to where you were running OK i.e. on  8.1.  We'll be issuing a new release shortly and you can try again with that, but make sure it is from a position where you are running OK and that you can easily revert.

**Comment by ury** [comment]
Will do, thanks!
