### ISSUE TITLE
Cannot build straight out of GitHub repos

### ISSUE THREAD

**Issue by tedneward** [NakedObjectsGroup/NakedObjectsFramework#7]
Steps to reproduce:

* VS 2015
* Clone project
* Look for any sort of build instructions in README.md or Documentation folder. None found.
* Open "all.sln". Click "Build Solution". 445 errors, owing to missing namespaces/assemblies.
* File open issue.

Suggested fix:
* Capture build process in README.md or another doc.

**Comment by richardpawson** [comment]
There is a section in the Developer Manual called 'How to build the framework from source'. (It involves running a build script  -  you can't just compile because the framework has many projects, each of which depends upon the others as packages. The  build script creates them all locally: its the same script we use to build the packages for subsequent publishing). 

However, the reason we don't have a link to this from the ReadMe is that there is no need to build the framework in order to use it: you are much better off using the framework as packages from the NuGet public gallery.  Indeed some of our long-term users have never, to the best of my knowledge, ever built the framework from source.  Building from source is really only necessary if you want to explore the internals, customise, or debug into the source.

**Comment by tedneward** [comment]
That's fair (and pretty much what I expected when I saw all the project files and solution files). However, I'd suggest that you put something in the README or in the Documentation folder (maybe the wiki? I dunno) that says pretty much what you're saying above.

The bigger issues, IMHO, are with the documentation around those who've never tried NOF before. Hence I filed a bunch of nits around NOF7 (since that's listed as the current stable).
