### ISSUE TITLE
MemberOrder

### ISSUE THREAD

**Issue by brentvee** [NakedObjectsGroup/NakedObjectsFramework#71]
Hi Richard,
Hope you're well.
We're still using NOF 7 sadly. I just haven't had the capacity to move to 8 yet.
I have a quick question though regarding the MemberOrder attribute.

When doing an ```Html.PropertyList(Model)``` the properties are displayed in their correct order as per the attribute.
I use ```Html.PropertyListWith(Model, properties)``` often but I've noticed that this does not respect the MemberOrder specified.
Is this the intended behaviour because I'm specifying a subset of properties?
If so, do I need to do my own reflection to determine the order?

Many thanks

**Comment by richardpawson** [comment]
FYI, we're quite close to releasing NOF9 now  -  it is already out in Beta and should go to RC in a week or so  -  so don't bother with NOF8. NOF9 is a change to the client only, not the server -  same look and feel but written on the new Angular framework.

Also, bear in mind that because NOF8 and NOF9 work with version 7 of the ProgrammingModel, you can have a NOF8/9 Run project alongside your NOF7 run project and talking to the same domain model projects.  This means that you can test the new UI on live systems without any big-bang changeover  -  this is what we are doing in Ireland. 

Back to your question.  I can't say for sure that Html.PropertyListWith(Model, properties) was intended to ignore MemberOrder or not, but it does not surprise me that it does (ignore it)  -  as that helper was intended for use in custom views, where it was assumed that you were specifying the order in the view.  I would have thought (though I am not sure, and haven't tested it) that this method renders the properties in the order they are listed in the 'properties' parameter, rather than the MemberOrder in domain code.  But, either way, if it does not do what you need you might have to write your own helper method.

**Comment by brentvee** [comment]
Thanks Richard,
Ok I've confirmed that ```Html.PropertyListWith(Model, properties)``` renders in the order given and does not user the MemberOrder attribute.
I'll work-around with reflection.

Hopefully I get a chance sometime in the future to have a look at NOF8/9 again.
Thanks again
