### ISSUE TITLE
better error message for locating service

### ISSUE THREAD

**Issue by smiltenburg** [NakedObjectsGroup/NakedObjectsFramework#95]
Hi, 

I'm in the process of migrating a NOF7 application to NOF9.
I just got stuck on an error message I found rather vague (took some time figuring out). 

Error message: Failed to Load Specification for: DomainModel.Repositories.TestService error: unexpected null

This error happened because I was adding the "TestService" to the IMenu array in the MainMenus method in the NakedObjectsRunSettings class. and this type was not returned in the getter of the "Services " property on the same class.

perhaps a more clear error would be.
"could not retrieve specification for service xxx. Services should be registred in/with the NakedObjectsRuntimeSettings.Services property

**Comment by richardpawson** [comment]
Thanks for the suggestion  -  but please see ticket #69, which has our preferred approach for this particular issue.

(Note that we could not simply change the error message because there are multiple circumstances that can give rise to that error  -  and by the time the code gets to it it would not be feasible to determine the  cause.)
